export const ROOMS = {
  MENTOR_ROOM: 'MENTOR_ROOM',
  PERSONAL_MESSAGE: 'PERSONAL_MESSAGE',
  NOTIFICATION: 'NOTIFICATION',
  POST_REQUEST: 'REQUEST',
  DEFAULT_ROOM: 'DEFAULT_ROOM',
};

export const EVENTS = {
  CONNECTION_ERROR: 'CONNECTION_ERROR',
  POST_REQUEST: 'REQUEST',
  MENTOR_ROOM: 'MENTOR_ROOM',
  PERSONAL_MESSAGE: 'PERSONAL_MESSAGE',
  NOTIFICATION: 'NOTIFICATION',
  DEFAULT_ROOM: 'DEFAULT_ROOM',
  REQUEST_DATA: 'REQUEST_DATA',
};

export const MESSAGE_TYPES = {
  REQUEST: 'REQUEST',
  CHAT: 'CHAT',
  NOTIFICATION: 'NOTIFICATION',
  FREE_SESSION_LINK: 'FREE_SESSION_LINK',
  PAID_SESSION_LINK: 'PAID_SESSION_LINK',
  START_PAID_SESSION: 'START_PAID_SESSION',
};

export const USER_TYPES = {
  MENTOR: 'MENTOR',
  MENTEE: 'MENTEE',
  ADMIN: 'ADMIN',
};

export const SESSION_STATUS = {
  REFUND: 'REFUND',
  COMPLETED: 'COMPLETED',
  INPROGRESS: 'INPROGRESS',
  OPEN: 'OPEN',
  REVIEW: 'REVIEW',
};
